site_name: TFC的笔记本
site_url: https://vting-tfc.top
site_author: TFC
site_description: 一个做笔记的地方
repo_url: https://github.com/iqdxa/Blog

# 导航栏菜单结构，层级与目录结构对应
nav:
  - 首页: index.md
  - 学习:
    - FPGA:
      - 初学者FPGA开发板选择: 学习/FPGA/初学者FPGA开发板选择.md
      - FPGA标准工程文件格式: 学习/FPGA/FPGA标准工程文件格式.md
      - FPGA程序固化方法: 学习/FPGA/FPGA程序固化方法.md
      - Vivado常见报错及解决办法: 学习/FPGA/Vivado常见报错及解决办法.md
      - HDLBits练习: 
        - Getting Started:
          - Step one: 学习/FPGA/HDLBits练习/GettingStarted/Step_one.md
          - Zero: 学习/FPGA/HDLBits练习/GettingStarted/Zero.md
        - Verilog Language:
          - Basics:
            - Wire: 学习/FPGA/HDLBits练习/VerilogLanguage/Basics/Wire.md
            - Wire4: 学习/FPGA/HDLBits练习/VerilogLanguage/Basics/Wire4.md
            - Notgate: 学习/FPGA/HDLBits练习/VerilogLanguage/Basics/Notgate.md
            - Andgate: 学习/FPGA/HDLBits练习/VerilogLanguage/Basics/Andgate.md
            - Norgate: 学习/FPGA/HDLBits练习/VerilogLanguage/Basics/Norgate.md
            - Xnorgate: 学习/FPGA/HDLBits练习/VerilogLanguage/Basics/Xnorgate.md
            - Wire decl: 学习/FPGA/HDLBits练习/VerilogLanguage/Basics/Wire_decl.md
            - 7485: 学习/FPGA/HDLBits练习/VerilogLanguage/Basics/7485.md
          - Vectors:
            - Vector0: 学习/FPGA/HDLBits练习/VerilogLanguage/Vectors/Vector0.md
            - Vector1: 学习/FPGA/HDLBits练习/VerilogLanguage/Vectors/Vector1.md
            - Vector2: 学习/FPGA/HDLBits练习/VerilogLanguage/Vectors/Vector2.md
            - Vectorgates: 学习/FPGA/HDLBits练习/VerilogLanguage/Vectors/Vectorgates.md
            - Gates4: 学习/FPGA/HDLBits练习/VerilogLanguage/Vectors/Gates4.md
            - Vector3: 学习/FPGA/HDLBits练习/VerilogLanguage/Vectors/Vector3.md
            - Vectorr: 学习/FPGA/HDLBits练习/VerilogLanguage/Vectors/Vectorr.md
            - Vector4: 学习/FPGA/HDLBits练习/VerilogLanguage/Vectors/Vector4.md
            - Vector5: 学习/FPGA/HDLBits练习/VerilogLanguage/Vectors/Vector5.md
          - Module：Hierarchy:
            - Module: 学习/FPGA/HDLBits练习/VerilogLanguage/Module：Hierarchy/Module.md
            - Module pos: 学习/FPGA/HDLBits练习/VerilogLanguage/Module：Hierarchy/Module_pos.md
            - Module name: 学习/FPGA/HDLBits练习/VerilogLanguage/Module：Hierarchy/Module_name.md
            - Module shift: 学习/FPGA/HDLBits练习/VerilogLanguage/Module：Hierarchy/Module_shift.md
            # - Module shift8: 学习/FPGA/HDLBits练习/VerilogLanguage/Module：Hierarchy/Module_shift8.md
            - Module add: 学习/FPGA/HDLBits练习/VerilogLanguage/Module：Hierarchy/Module_add.md
            - Module fadd: 学习/FPGA/HDLBits练习/VerilogLanguage/Module：Hierarchy/Module_fadd.md
            - Module cseladd: 学习/FPGA/HDLBits练习/VerilogLanguage/Module：Hierarchy/Module_cseladd.md
            - Module addsub: 学习/FPGA/HDLBits练习/VerilogLanguage/Module：Hierarchy/Module_addsub.md
          - Procedures:
            - Alwaysblock1: 学习/FPGA/HDLBits练习/VerilogLanguage/Procedures/Alwaysblock1.md
            - Alwaysblock2: 学习/FPGA/HDLBits练习/VerilogLanguage/Procedures/Alwaysblock2.md
            - Always if: 学习/FPGA/HDLBits练习/VerilogLanguage/Procedures/Always_if.md
            - Always if2: 学习/FPGA/HDLBits练习/VerilogLanguage/Procedures/Always_if2.md
            - Always case: 学习/FPGA/HDLBits练习/VerilogLanguage/Procedures/Always_case.md
            - Always case2: 学习/FPGA/HDLBits练习/VerilogLanguage/Procedures/Always_case2.md
            - Always casez: 学习/FPGA/HDLBits练习/VerilogLanguage/Procedures/Always_casez.md
            - Always nolatches: 学习/FPGA/HDLBits练习/VerilogLanguage/Procedures/Always_nolatches.md
          - MoreVerilogFeatures:
            - Conditional: 学习/FPGA/HDLBits练习/VerilogLanguage/MoreVerilogFeatures/Conditional.md
            - Reduction: 学习/FPGA/HDLBits练习/VerilogLanguage/MoreVerilogFeatures/Reduction.md
            - Gates100: 学习/FPGA/HDLBits练习/VerilogLanguage/MoreVerilogFeatures/Gates100.md
            - Vector100r: 学习/FPGA/HDLBits练习/VerilogLanguage/MoreVerilogFeatures/Vector100r.md
        - Circuits:
          - ConbinationalLogic:
            - BasicGates:
              - Wire: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Wire.md
              - GND: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/GND.md
              - NOR: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/NOR.md
              - Another gate: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Another_gate.md
              - Two gates: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Two_gates.md
              - Gates: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Gates.md
              - 7420: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/7420.md
              - Truthtable1: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Truthtable1.md
              - Mt2015 eq2: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Mt2015_eq2.md
              - Mt2015 q4a: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Mt2015_q4a.md
              - Mt2015 q4b: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Mt2015_q4b.md
              - Mt2015 q4: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Mt2015_q4.md
              - Ringer: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Ringer.md
              - Thermostat: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Thermostat.md
              - Popcount3: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Popcount3.md
              - Gatesv: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Gatesv.md
              - Gatesv100: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/BasicGates/Gatesv100.md
            - Multiplexers:
              - Mux2to1: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/Multiplexers/Mux2to1.md
              - Mux2to1v: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/Multiplexers/Mux2to1v.md
              - Mux9to1v: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/Multiplexers/Mux9to1v.md
              - Mux256to1: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/Multiplexers/Mux256to1.md
              - Mux256to1v: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/Multiplexers/Mux256to1v.md
            - ArithmeticCircuits: 
              - Hadd: 学习/FPGA/HDLBits练习/Circuits/ConbinationalLogic/ArithmeticCircuits/Hadd.md
    - Rust:
      - Burn导入问题: 学习/Rust/Burn导入问题.md
    - Android:
      - 使用ADB卸载手机系统应用: 学习/Android/使用ADB卸载手机系统应用.md
    - Linux:
      - 退出vim的方法: 学习/Linux/退出Vim的方法.md
    - MarkDown:
      - 强调语法: 学习/MarkDown/强调语法.md
    - MkDocs:
      - MkDocs安装教程: 学习/MkDocs/MkDocs安装教程.md
    - 其他:
      - 知网研学:
        - 知网研学登录失败解决办法: 学习/其他/知网研学/知网研学登录失败解决办法.md
  - 娱乐:
    - 我的世界:
      - PCL正版验证问题: 娱乐/我的世界/PCL正版验证问题.md
    - 缺氧:
      - 缺氧经验总结: 娱乐/缺氧/缺氧经验总结.md

# 设置主题
theme:
  name: material
  logo: assets/logo.jpg # 网站logo
  favicon: images/favicon.jpg # 网站图标
  features:
    - navigation.tabs      # 顶部标签页导航
    - navigation.sections  # 自动提取标题生成章节锚点
    - content.code.copy    # 代码复制
    - content.code.annotate  
  palette:
    - scheme: default      # 浅色模式
    - scheme: slate        # 暗黑模式（用户可切换）

plugins:
  - tags:
      tags_file: tags.md # (1)!

markdown_extensions:
  # 代码块
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # 提示块
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # 显示属于提示
  - abbr
  - pymdownx.snippets

  # 内容标签页
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  # 表格
  - tables

  # 脚注
  - footnotes