site_name: TFC的笔记本
site_url: https://vting-tfc.top
site_author: TFC
site_description: 一个做笔记的地方
repo_url: https://github.com/iqdxa/Blog

# 导航栏菜单结构，层级与目录结构对应
nav:
  - 首页: index.md
  - 学习:
    - FPGA:
      - 初学者FPGA开发板选择: 学习/FPGA/初学者FPGA开发板选择.md
      - FPGA标准工程文件格式: 学习/FPGA/FPGA标准工程文件格式.md
      - FPGA程序固化方法: 学习/FPGA/FPGA程序固化方法.md
      - HDLBits练习: 
        - Getting Started:
          - Step one: 学习/FPGA/HDLBits练习/GettingStarted/Step_one.md
          - Zero: 学习/FPGA/HDLBits练习/GettingStarted/Zero.md
        - Verilog Language:
          - Wire: 学习/FPGA/HDLBits练习/VerilogLanguage/Wire.md
          - Wire4: 学习/FPGA/HDLBits练习/VerilogLanguage/Wire4.md
          - Notgate: 学习/FPGA/HDLBits练习/VerilogLanguage/Notgate.md
          - Andgate: 学习/FPGA/HDLBits练习/VerilogLanguage/Andgate.md
          - Norgate: 学习/FPGA/HDLBits练习/VerilogLanguage/Norgate.md
          - Xnorgate: 学习/FPGA/HDLBits练习/VerilogLanguage/Xnorgate.md
          - Wire decl: 学习/FPGA/HDLBits练习/VerilogLanguage/Wire_decl.md
          - 7485: 学习/FPGA/HDLBits练习/VerilogLanguage/7485.md
    - Rust:
      - Burn导入问题: 学习/Rust/Burn导入问题.md
    - Android:
      - 使用ADB卸载手机系统应用: 学习/Android/使用ADB卸载手机系统应用.md
    - Linux:
      - 退出vim的方法: 学习/Linux/退出Vim的方法.md
    - MarkDown:
      - 强调语法: 学习/MarkDown/强调语法.md
    - MkDocs:
      - MkDocs安装教程: 学习/MkDocs/MkDocs安装教程.md
    - 其他:
      - 知网研学:
        - 知网研学登录失败解决办法: 学习/其他/知网研学/知网研学登录失败解决办法.md
  - 娱乐:
    - 我的世界:
      - PCL正版验证问题: 娱乐/我的世界/PCL正版验证问题.md
    - 缺氧:
      - 缺氧经验总结: 娱乐/缺氧/缺氧经验总结.md

# 设置主题
theme:
  name: material
  features:
    - navigation.tabs      # 顶部标签页导航
    - navigation.sections  # 自动提取标题生成章节锚点
    - content.code.copy    # 代码复制
    - content.code.annotate  
  palette:
    - scheme: default      # 浅色模式
    - scheme: slate        # 暗黑模式（用户可切换）

markdown_extensions:
  # 代码块
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # 提示块
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # 显示属于提示
  - abbr
  - pymdownx.snippets

  # 内容标签页
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  # 表格
  - tables

  # 脚注
  - footnotes